### ISSUE TITLE
How are conditions supported in the interfaces?

### ISSUE THREAD

**Issue by whiskeysierra** [zalando-incubator/baigan-config#3]
I couldn't find an example on how to use conditions in the readme.

**Comment by amjedonline** [comment]
In the readme you just find the Equals condition for now, atm we have another In condition, which takes a list of values to compare. But you could writing your own Conditions by implementing the ConditionType interface.

**Comment by whiskeysierra** [comment]
But how do I use conditions with e.g. the express feature?

    @BaiganConfig
    public interface ExpressFeature {

        // where do I put the country code?
        public Boolean enabled();

    }

**Comment by amjedonline** [comment]
_country_code_ is a _context_ parameter. There could be many more _context_ parameters. They get provisioned with the help of _ContextProvider_s. Here is an example _ContextProvider_:

```java
@Component
public class WebContextProvider implements ContextProvider {

    private final Set<String> PARAMS = ImmutableSet.of("country_code",
            "customerType");

    @Override
    public String getContextParam(String name) {
        return WebContextHolder.get().get(name);
    }

    @Override
    public Set<String> getProvidedContexts() {
        return PARAMS;
    }
}
```

NB: Context parameters are not mandatory. One could have defaultValue and that should suffice for simple use cases.

**Comment by whiskeysierra** [comment]
I don't get it. How does that play together with the auto-generated proxies?

**Comment by amjedonline** [comment]
the _ConfigurationContextProviderBeanPostprocessor_ registers all the ContextProviders in a _ContextProviderRegistry_ . The auto-generated proxies simply delegates the method calls to a _ContextAwareConfigurationMethodInvocationHandler_ , this handler in turn fetch itself the registered _ContextProvider_ corresponding to the context parameter and gets the value for the context parameter.

**Comment by whiskeysierra** [comment]
So there is no support to put the country code as a simple method parameter?

**Comment by amjedonline** [comment]
yes. the idea is to keep the configuration interface simple and stupid. The default value, conditions and context parameters based rules are defined as part of the configuration. 
## With this 
1. You could add more/remove context parameters without having to change the actual code.
2. Don't have boiler plate code of finding context params bleeding all over the place.

**Comment by whiskeysierra** [comment]
But those context values usually come directly from my domain models, i.e. I have them at hand when I evaluate some configuration keys. At least for us, this is usually the case.

**Comment by amjedonline** [comment]
IMHO looks like the ideal solution would be to have possibility to 
1. Define method parameters
2. Use method parameters values over values from provider.

what do you think ?

**Comment by amjedonline** [comment]
So one simple possibility I could think of achieving this is:
1. Have a way have an hypothetical annotation _@ContextParam("paramName")_ .
2. The MethodInvocationHandler looks for annotated method parameters and associates the contextParam name with the argument value.
3. This context param value overrides the values from other _ContextProvider_s if they exist at all.
4. Enabling you to a)Completely forego defining ContextProvider b) Still use ContextParam in configuration c) Pass your _ContextParam_'s value at the config method invocation.

Example: Addressing @whiskeysierra usage 

**Config class definition**
```
@BaiganConfig
public interface ExpressFeature {
    public Boolean enabled(@ContextParam("country_code") final String countryCode );
}

```

**Config method invocation**
`boolean isExpressFeatureEnable = expressFeature.enabled("de");`

@whiskeysierra @lmineiro @mostlymagic  your opinions ?
